### ISSUE TITLE
bump peerDependency

### ISSUE THREAD

**Issue by rstacruz** [troch/deku-redux#1]
deku 1.0.0 is out.

**Comment by kesla** [comment]
+:1:

**Comment by kesla** [comment]
:+1:

**Comment by rstacruz** [comment]
actually, deku 2.0.0 is out and will not need deku-redux anymore. how about bumping it to deku `<2`?

**Comment by troch** [comment]
1.1.0 released. As you said no need for deku 2.0.0 for now.
